package server.messaging

/**
 * Network message constants from server to client.
 *
 * From `ServerNotificationConstants.as`
 *
 * Related: [ClientMessage]
 */
@Suppress("Unused", "SpellCheckingInspection")
object ServerMessage {
    const val SERVER_MESSAGE_: String = "SERVER_MESSAGE_"
    const val CLIENT_MESSAGE_: String = "CLIENT_MESSAGE_"
    const val CLIENT_MESSAGE_TEST: String = "CLIENT_MESSAGE_TEST"
    const val SERVER_NEW: String = "SERVER_NEW"
    const val SERVER_NEW_MESSAGE: String = "SERVER_NEW_MESSAGE"
    const val SERVER_CONNECTED: String = "SERVER_CONNECTED"
    const val SERVER_CONNECTION_CLOSED: String = "SERVER_CONNECTION_CLOSED"
    const val SERVER_CONNECTION_IDLE_CLOSE: String = "CONNECTION_IDLE_CLOSE"
    const val SERVER_ILLEGAL_PARAM_FAIL: String = "ILLEGAL_PARAM_FAIL"
    const val SERVER_PUSH_MAINTENANCE: String = "SERVER_PUSH_MAINTENANCE"
    const val SERVER_PUSH_SHUTDOWN: String = "SERVER_PUSH_SHUTDOWN"
    const val SERVER_PUSH_RECONNECT: String = "SERVER_PUSH_RECONNECT"
    const val SERVER_MESSAGE_PROGRESS: String = "SERVER_MESSAGE_PROGRESS"
    const val SERVER_MESSAGE_SPOOL: String = "SPOOL"
    const val SERVER_MESSAGE_HARVESTHELPER_RESIDENTIAL_SUCCESS_SPOOL: String =
        "HARVESTHELPER_RESIDENTIAL_SUCCESS_SPOOL"
    const val CLIENT_MESSAGE_LOGIN: String = "LOGIN"
    const val SERVER_MESSAGE_INITIAL_LOGIN_SUCCESS: String = "LOGIN_SUCCESS"
    const val SERVER_MESSAGE_LOGIN_FAILED: String = "LOGIN_FAILED"
    const val CLIENT_MESSAGE_LOGOUT: String = "LOGOUT"
    const val CLIENT_MESSAGE_TIMESTAMP_REQUEST: String = "TIMESTAMP_REQUEST"
    const val SERVER_MESSAGE_TIMESTAMP_RESPONSE: String = "TIMESTAMP_RESPONSE"
    const val SERVER_MESSAGE_MIDSESSION_LOGIN_SUCCESS: String = "LOGIN_SUCCESS"
    const val CLIENT_MESSAGE_SWITCH_PLAYFIELD: String = "SWITCH_PLAYFIELD"
    const val CLIENT_MESSAGE_PLAYFIELD_LOAD: String = "PLAYFIELD_LOAD"
    const val SERVER_MESSAGE_PLAYFIELD_PLAYFIELDITEM_DELETE_SUCCESS: String =
        "PLAYFIELDITEM_DELETE_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_PLAYFIELDITEM_DELETE_FAILED: String =
        "PLAYFIELDITEM_DELETE_FAILED"
    const val CLIENT_MESSAGE_PLAYFIELD_BUILDING_DELETE: String = "PLAYFIELD_BUILDING_DELETE"
    const val CLIENT_MESSAGE_PLAYFIELD_ITEM_CREATE: String = "PLAYFIELD_ITEM_CREATE"
    const val CLIENT_MESSAGE_PLAYFIELD_DECORATION_CREATE: String = "PLAYFIELD_DECORATION_CREATE"
    const val CLIENT_MESSAGE_PLAYFIELD_DECORATION_MOVE: String = "PLAYFIELD_DECORATION_MOVE"
    const val CLIENT_MESSAGE_PLAYFIELD_DECORATION_DELETE: String = "PLAYFIELD_DECORATION_DELETE"
    const val SERVER_MESSAGE_PLAYFIELD_CREATE_DECORATION_FAILED: String =
        "PLAYFIELD_CREATE_DECORATION_FAILED"
    const val SERVER_MESSAGE_PLAYFIELD_CREATE_DECORATION_SUCCESS: String =
        "PLAYFIELD_CREATE_DECORATION_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_MOVE_DECORATION_SUCCESS: String =
        "PLAYFIELD_MOVE_DECORATION_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_MOVE_DECORATION_FAILED: String =
        "PLAYFIELD_MOVE_DECORATION_FAILED"
    const val SERVER_MESSAGE_PLAYFIELD_DELETE_DECORATION_SUCCESS: String =
        "PLAYFIELD_DELETE_DECORATION_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_DELETE_DECORATION_FAILED: String =
        "PLAYFIELD_DELETE_DECORATION_FAILED"
    const val CLIENT_MESSAGE_PLAYFIELD_BUILDING_CREATE: String = "PLAYFIELD_BUILDING_CREATE"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_NEW: String = "PLAYFIELD_BUILDING_NEW"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_CREATE_FAILED: String =
        "PLAYFIELD_BUILDING_CREATE_FAILED"
    const val CLIENT_MESSAGE_PLAYFIELD_BUILDING_CONSTRUCTIONPHASE_PROCESS: String =
        "PLAYFIELD_BUILDING_PROCESSPHASE"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_CONSTRUCTIONPHASE_UPDATE: String =
        "PLAYFIELD_BUILDING_CONSTRUCTIONPHASE_UPDATE"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_HARVESTPHASE_UPDATE: String =
        "PLAYFIELD_BUILDING_HARVESTPHASE_UPDATE"
    const val CLIENT_MESSAGE_PLAYFIELD_CREATE_GROUND: String = "PLAYFIELD_CREATE_GROUND"
    const val SERVER_MESSAGE_PLAYFIELD_CREATE_GROUND_SUCCESS: String =
        "PLAYFIELD_CREATE_GROUND_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_CREATE_GROUND_FAILED: String = "PLAYFIELD_CREATE_GROUND_FAILED"
    const val SERVER_MESSAGE_PLAYFIELD_UPDATE_GROUND_SUCCESS: String =
        "PLAYFIELD_UPDATE_GROUND_SUCCESS"
    const val CLIENT_MESSAGE_PLAYFIELD_DESTROY_GROUND: String = "PLAYFIELD_DESTROY_GROUND"
    const val SERVER_MESSAGE_PLAYFIELD_DESTROY_GROUND_SUCCESS: String =
        "PLAYFIELD_DESTROY_GROUND_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_DESTROY_GROUND_FAILED: String =
        "PLAYFIELD_DESTROY_GROUND_FAILED"
    const val CLIENT_MESSAGE_PLAYFIELD_MOVE_GROUND: String = "PLAYFIELD_MOVE_GROUND"
    const val SERVER_MESSAGE_PLAYFIELD_MOVE_GROUND_SUCCESS: String = "PLAYFIELD_MOVE_GROUND_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_MOVE_GROUND_FAILED: String = "PLAYFIELD_MOVE_GROUND_FAILED"
    const val CLIENT_MESSAGE_PLAYFIELD_BUILDING_INAUGURATE: String = "PLAYFIELD_BUILDING_INAUGURATE "
    const val CLIENT_MESSAGE_PLAYFIELD_BUILDING_SWAP_RESIDENT: String =
        "PLAYFIELD_BUILDING_SWAP_RESIDENT"
    const val SERVER_MESSAGE_PLAYFIELD_SWITCH_SUCCESS: String = "PLAYFIELD_SWITCH_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_BOULDER_CREATED: String = "PLAYFIELD_BOULDER_CREATED"
    const val CLIENT_MESSAGE_PLAYFIELD_BOULDER_PROCESSPHASE: String = "PLAYFIELD_BOULDER_PROCESSPHASE"
    const val SERVER_MESSAGE_PLAYFIELD_BOULDER_PHASE_STARTED: String =
        "PLAYFIELD_BOULDER_PHASE_STARTED"
    const val SERVER_MESSAGE_PLAYFIELD_BOULDER_DESTRUCTIONPHASE_UPDATE: String =
        "PLAYFIELD_BOULDER_DESTRUCTIONPHASE_UPDATE"
    const val SERVER_MESSAGE_PLAYFIELD_BOULDER_DELETED: String = "PLAYFIELD_BOULDER_DELETED"
    const val CLIENT_MESSAGE_PLAYFIELDITEM_BUY_PERMISSION: String = "PLAYFIELDITEM_BUY_PERMISSION"
    const val SERVER_MESSAGE_PLAYFIELDITEM_BUY_PERMISSION_FAIL: String =
        "PLAYFIELDITEM_BUY_PERMISSION_FAIL"
    const val CLIENT_MESSAGE_PLAYFIELD_BUILDING_BOOSTPHASE: String = "PLAYFIELD_BUILDING_BOOSTPHASE"
    const val SERVER_MESSAGE_PLAYFIELD_ITEM_BOOSTPHASE_UPDATE: String =
        "PLAYFIELD_ITEM_BOOSTPHASE_UPDATE"
    const val CLIENT_MESSAGE_PLAYFIELD_REQUEST_INSTANTFINISH: String =
        "PLAYFIELD_REQUEST_INSTANTFINISH"
    const val SERVER_MESSAGE_RESOURCES: String = "RESOURCES"
    const val SERVER_MESSAGE_QUEST_NEW: String = "QUEST_NEW"
    const val SERVER_MESSAGE_QUEST_TASK_UPDATE: String = "QUEST_TASK_UPDATE"
    const val SERVER_MESSAGE_QUEST_UPDATE: String = "QUEST_UPDATE"
    const val SERVER_MESSAGE_PLAYER_LEVEL_UP_SUCCESS: String = "PLAYER_LEVEL_UP_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_UPDATE: String = "PLAYFIELD_UPDATE"
    const val SERVER_MESSAGE_PLAYFIELD_EXPAND_FAILED: String = "PLAYFIELD_EXPAND_FAILED"
    const val SERVER_MESSAGE_PLAYFIELD_EXPAND_SUCCESS: String = "PLAYFIELD_EXPAND_SUCCESS"
    const val CLIENT_MESSAGE_PLAYFIELD_EXPAND: String = "PLAYFIELD_EXPAND"
    const val CLIENT_PAYMENT_SWAP_CURRENCY: String = "PAYMENT_SWAP_CURRENCY"
    const val CLIENT_MESSAGE_PLAYFIELD_BUILDING_HARVESTPHASE_PROCESS: String =
        "PLAYFIELD_BUILDING_HARVESTPHASE_PROCESS"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_CONSTRUCTION_FINISHED: String =
        "PLAYFIELD_BUILDING_CONSTRUCTION_FINISHED"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_UPGRADEPHASE_UPDATE: String =
        "PLAYFIELD_BUILDING_UPGRADEPHASE_UPDATE"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_PHASE_NEW: String = "PLAYFIELD_BUILDING_PHASE_NEW"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_MOVE_FAILED: String = "PLAYFIELD_BUILDING_MOVE_FAILED"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_MOVE_SUCCESS: String =
        "PLAYFIELD_BUILDING_MOVE_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELDITEM_ACTIVE_STATE_CHANGED: String =
        "PLAYFIELDITEM_ACTIVE_STATE_CHANGED"
    const val CLIENT_MESSAGE_PLAYFIELD_HARVEST_PRODUCTION: String = "PLAYFIELD_HARVEST_PRODUCTION"
    const val CLIENT_MESSAGE_PLAYFIELD_CANCEL_PRODUCTION: String = "PLAYFIELD_CANCEL_PRODUCTION"
    const val CLIENT_MESSAGE_PLAYFIELD_REQUEST_PRODUCTION: String = "PLAYFIELD_REQUEST_PRODUCTION"
    const val SERVER_MESSAGE_PLAYFIELD_PRODUCTION_PHASEUPDATE: String =
        "PLAYFIELD_PRODUCTION_PHASEUPDATE"
    const val SERVER_MESSAGE_PLAYFIELD_PRODUCTION_FAILED: String = "PLAYFIELD_PRODUCTION_FAILED"
    const val SERVER_MESSAGE_PLAYFIELD_PRODUCTION_HARVEST_SUCCESS: String =
        "PLAYFIELD_PRODUCTION_HARVEST_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_PRODUCTION_HARVEST_FAILED: String =
        "PLAYFIELD_PRODUCTION_HARVEST_FAILED"
    const val SERVER_MESSAGE_PLAYFIELD_PRODUCTION_CANCEL_SUCCESS: String =
        "PLAYFIELD_PRODUCTION_CANCEL_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_PRODUCTION_CANCEL_FAILED: String =
        "PLAYFIELD_PRODUCTION_CANCEL_FAILED"
    const val CLIENT_MESSAGE_PLAYFIELD_MOVE_BUILDING: String = "PLAYFIELD_MOVE_BUILDING"
    const val SERVER_MESSAGE_PLAYFIELD_STACK_NEED_SUCCESS: String = "PLAYFIELD_STACK_NEED_SUCCESS"
    const val CLIENT_MESSAGE_PLAYFIELD_UNSTACK_NEED: String = "PLAYFIELD_UNSTACK_NEED"
    const val CLIENT_MESSAGE_PLAYFIELD_STACK_NEED: String = "PLAYFIELD_STACK_NEED"
    const val SERVER_MESSAGE_PLAYFIELD_NEED_CONSUMED: String = "PLAYFIELD_NEED_CONSUMED"
    const val CLIENT_MESSAGE_QUEST_TASK_PROCESS: String = "QUEST_TASK_PROCESS"
    const val CLIENT_MESSAGE_QUEST_ELEMENT_INSTANT_FINISH: String = "QUEST_ELEMENT_INSTANT_FINISH"
    const val SERVER_MESSAGE_SWITCH_FEATURE_ACTIVATION: String = "SWITCH_FEATURE_ACTIVATION"
    const val CLIENT_PLAYER_INVITE_REQUESTFRIENDLIST: String = "PLAYER_INVITE_REQUESTFRIENDLIST"
    const val CLIENT_PLAYER_INVITE_FRIEND: String = "PLAYER_INVITE_FRIEND"
    const val CLIENT_PLAYER_ACCEPT_FRIEND: String = "PLAYER_ACCEPT_FRIEND"
    const val CLIENT_PLAYER_DECLINE_FRIEND: String = "PLAYER_DECLINE_FRIEND"
    const val CLIENT_PLAYER_CANCEL_FRIEND: String = "PLAYER_CANCEL_FRIEND"
    const val SERVER_MESSAGE_FRIENDS_UPDATE: String = "FRIENDS_UPDATE"
    const val SERVER_MESSAGE_SLAYER_INVITE_FRIEND_SUCCESS: String = "SLAYER_INVITE_FRIEND_SUCCESS"
    const val SERVER_MESSAGE_SLAYER_INVITE_FRIEND_FAILED: String = "SLAYER_INVITE_FRIEND_FAILED"
    const val SERVER_MESSAGE_SLAYER_REQUEST_FRIENDLIST_FAILED: String =
        "SLAYER_REQUEST_FRIENDLIST_FAILED"
    const val SERVER_MESSAGE_EVENT_UPDATE: String = "EVENT_UPDATE"
    const val SERVER_MESSAGE_PMS_PUSH_NEW_MESSAGE: String = "PMS_PUSH_NEW_MESSAGE"
    const val SERVER_MESSAGE_PLAYER_BOOKED_PAYMENTPACK: String = "PLAYER_BOOKED_PAYMENTPACK"
    const val CLIENT_MESSAGE_QUEST_ELEMENT_CHANGE_STATE: String = "QUEST_ELEMENT_CHANGE_STATE"
    const val SERVER_MESSAGE_PLAYER_PAYMENTPACK_UPDATE: String = "PLAYER_PAYMENTPACK_UPDATE"
    const val SERVER_MESSAGE_QUEST_CHALLENGE_UPDATE: String = "QUEST_CHALLENGE_UPDATE"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_RESIDENT_SWAP_SUCCESS: String =
        "PLAYFIELD_BUILDING_RESIDENT_SWAP_SUCCESS"
    const val SERVER_MESSAGE_PLAYFIELD_BUILDING_RANDOM_DROP: String = "PLAYFIELD_BUILDING_RANDOM_DROP"
    const val SERVER_MESSAGE_MARKET_PUSH_NOTIFICATION_MESSAGE: String =
        "MARKET_PUSH_NOTIFICATION_MESSAGE"
    const val SERVER_MESSAGE_PLAYFIELD_EMERGENCY_UPDATE: String = "PLAYFIELD_EMERGENCY_UPDATE"
    const val SERVER_MESSAGE_PLAYFIELD_EMERGENCY_FINISH: String = "PLAYFIELD_EMERGENCY_FINISH"
    const val CLIENT_MESSAGE_PLAYFIELD_PROCESS_EMERGENCY: String = "PLAYFIELD_PROCESS_EMERGENCY"
    const val CLIENT_MESSAGE_PLAYFIELD_REPAIR_BUILDING: String = "PLAYFIELD_REPAIR_BUILDING"
    const val CLIENT_MESSAGE_PLAYFIELD_COLLECT_EMERGENCY: String = "PLAYFIELD_COLLECT_EMERGENCY"
    const val CLIENT_MESSAGE_PROFESSIONAL_DISMISS: String = "PROFESSIONAL_DISMISS"
    const val SERVER_MESSAGE_PROFESSIONAL_DISMISS_SUCCESS: String = "PROFESSIONAL_DISMISS_SUCCESS"
    const val SERVER_MESSAGE_PROFESSIONAL_DISMISS_FAILED: String = "PROFESSIONAL_DISMISS_FAILED"
    const val CLIENT_MESSAGE_PROFESSIONAL_CREATE: String = "PROFESSIONAL_CREATE"
    const val SERVER_MESSAGE_PROFESSIONAL_CREATE_SUCCESS: String = "PROFESSIONAL_CREATE_SUCCESS"
    const val SERVER_MESSAGE_PROFESSIONAL_CREATE_FAILED: String = "PROFESSIONAL_CREATE_FAILED"
    const val SERVER_MESSAGE_PROFESSIONAL_CHANGE_SUCCESS: String = "PROFESSIONAL_CHANGE_SUCCESS"
    const val SERVER_MESSAGE_PROFESSIONAL_CHANGE_FAIL: String = "PROFESSIONAL_CHANGE_FAIL"
    const val CLIENT_MESSAGE_PROFESSIONAL_FIRE: String = "PROFESSIONAL_FIRE"
    const val CLIENT_MESSAGE_PROFESSIONAL_RENEW: String = "PROFESSIONAL_RENEW"
    const val CLIENT_MESSAGE_BOOSTERPACK_BUY: String = "BOOSTERPACK_BUY"
    const val SERVER_MESSAGE_BOOSTER_REWARD_SUCCESS: String = "BOOSTER_REWARD_SUCCESS"
    const val SERVER_MESSAGE_EDUCATION_CREATED: String = "EDUCATION_CREATED"
    const val CLIENT_MESSAGE_ADD_EDUCATION_STEP: String = "ADD_EDUCATION_STEP"
    const val CLIENT_MESSAGE_START_EDUCATION: String = "START_EDUCATION"
    const val CLIENT_MESSAGE_SPEND_SKILLPOINT: String = "SPEND_SKILLPOINT"
    const val CLIENT_MESSAGE_HIRE_PROFESSIONAL: String = "HIRE_PROFESSIONAL"
    const val SERVER_MESSAGE_EDUCATION_EXTEND_SUCCESS: String = "EDUCATION_EXTEND_SUCCESS"
    const val SERVER_MESSAGE_EDUCATION_EXTEND_FAIL: String = "EDUCATION_EXTEND_FAIL"
    const val SERVER_MESSAGE_START_EDUCATION_SUCCESS: String = "START_EDUCATION_SUCCESS"
    const val SERVER_MESSAGE_START_EDUCATION_FAIL: String = "START_EDUCATION_FAIL"
    const val SERVER_MESSAGE_PROFESSIONAL_ATTRIBUTE_CHANGE_SUCCESS: String =
        "PROFESSIONAL_ATTRIBUTE_CHANGE_SUCCESS"
    const val SERVER_MESSAGE_PROFESSIONAL_ATTRIBUTE_CHANGE_FAIL: String =
        "PROFESSIONAL_ATTRIBUTE_CHANGE_FAIL"
    const val SERVER_MESSAGE_EDUCATION_FINISHED: String = "EDUCATION_FINISHED"
    const val SERVER_MESSAGE_PROFESSIONAL_ASSIGNED_SUCCESS: String = "PROFESSIONAL_ASSIGNED_SUCCESS"
    const val SERVER_MESSAGE_PROFESSIONAL_SPECIALIZATION_CHANGE: String =
        "PROFESSIONAL_SPECIALIZATION_CHANGE"
    const val CLIENT_MESSAGE_MOVE_INVENTORYITEM_TO_PLAYFIELD: String =
        "MOVE_INVENTORYITEM_TO_PLAYFIELD "
    const val CLIENT_MESSAGE_MOVE_PLAYFIELDITEM_TO_INVENTORY: String =
        "MOVE_PLAYFIELDITEM_TO_INVENTORY "
    const val CLIENT_MESSAGE_REMOVE_ITEM_FROM_INVENTORY: String = "DELETE_INVENTORYITEM"
    const val SERVER_MESSAGE_INVENTORY_UPDATE: String = "INVENTORY_UPDATE"
    const val CLIENT_MESSAGE_EXPAND_INVENTORY_BAG: String = "EXPAND_INVENTORY_BAG"
    const val SERVER_MESSAGE_EXPAND_INVENTORY_BAG_SUCCESS: String = "EXPAND_INVENTORY_BAG_SUCCES"
    const val CLIENT_MESSAGE_PLAYFIELD_USE_HARVESTHELPER_RESIDENTIAL: String =
        "PLAYFIELD_USE_HARVESTHELPER_RESIDENTIAL"
    const val SERVER_MESSAGE_PLAYER_CITY_UPDATE: String = "PLAYER_CITY_UPDATE"
    const val CLIENT_MESSAGE_PROFESSIONAL_LEVEL_UP: String = "PROFESSIONAL_LEVEL_UP"
    const val SERVER_MESSAGE_PROFESSIONAL_LEVEL_SUCCESS: String = "PROFESSIONAL_LEVEL_SUCCESS"
    const val SERVER_MESSAGE_PROFESSIONAL_TRAIT_SUCCESS: String = "PROFESSIONAL_TRAIT_SUCCESS"
    const val SERVER_MESSAGE_PLAYER_NEWSSCREEN_UPDATE: String = "PLAYER_NEWSSCREEN_UPDATE"
    const val CLIENT_MESSAGE_PLAYER_REQUEST_NEWSSCREEN: String = "PLAYER_REQUEST_NEWSSCREEN"
    const val CLIENT_MESSAGE_EQUIP_PLAYFIELDITEM_IMPROVEMENT: String =
        "EQUIP_PLAYFIELDITEM_IMPROVEMENT"
    const val SERVER_MESSAGE_PLAYFIELDITEM_IMPROVEMENT_EQUIPPED: String =
        "PLAYFIELDITEM_IMPROVEMENT_EQUIPPED"
    const val CLIENT_MESSAGE_PROLONG_PLAYFIELDITEM_IMPROVEMENT: String =
        "PROLONG_PLAYFIELDITEM_IMPROVEMENT"
    const val SERVER_MESSAGE_PLAYFIELDITEM_IMPROVEMENT_UPDATED: String =
        "PLAYFIELDITEM_IMPROVEMENT_UPDATED"
    const val CLIENT_MESSAGE_DELETE_PLAYFIELDITEM_IMPROVEMENT: String =
        "DELETE_PLAYFIELDITEM_IMPROVEMENT"
    const val SERVER_MESSAGE_PLAYFIELDITEM_IMPROVEMENT_DELETED: String =
        "PLAYFIELDITEM_IMPROVEMENT_DELETED"
    const val CLIENT_MESSAGE_IMPROVEMENT_BOOSTER_BUY: String = "IMPROVEMENT_BOOSTER_BUY"
    const val SERVER_MESSAGE_IMPROVEMENT_BOOSTER_REWARD_SUCCESS: String =
        "IMPROVEMENT_BOOSTER_REWARD_SUCCESS"
    const val SERVER_MESSAGE_PLAYER_FEATURE_UPDATE: String = "PLAYER_FEATURE_UPDATE"
    const val SERVER_MESSAGE_CITY_WHEEL_UPDATE: String = "CITY_WHEEL_UPDATE"
    const val CLIENT_MESSAGE_CITY_WHEEL_SPIN: String = "CITY_WHEEL_SPIN"
    const val CLIENT_MESSAGE_CITY_WHEEL_COLLECT: String = "CITY_WHEEL_COLLECT"
    const val CLIENT_MESSAGE_MASTERY_BUILDING_PROCESS: String = "MASTERY_BUILDING_PROCESS"
    const val SERVER_MESSAGE_MASTERY_CHALLENGE_UPDATE: String =
        "PLAYFIELD_BUILDING_MASTERY_CHALLENGE_UPDATE"
    const val SERVER_MESSAGE_MASTERY_BONUS_UPDATE: String = "PLAYFIELD_BUILDING_MASTERY_BONUS_UPDATE"
    const val SERVER_MESSAGE_CINEMA_UPDATE: String = "CINEMA_UPDATE"
    const val SERVER_MESSAGE_PLAYER_PAYMENT_UPSELL_UPDATE: String = "PLAYER_PAYMENT_UPSELL_UPDATE"
    const val CLIENT_MESSAGE_UPDATE_CLIENT_UI_DATA: String = "UPDATE_CLIENT_UI_DATA"
    const val SERVER_MESSAGE_UPDATE_CLIENT_UI_DATA_SUCCESS: String = "UPDATE_CLIENT_UI_DATA_SUCCESS"
    const val SET_USER_OPTIONS: String = "SET_USER_OPTIONS"
}
