package core.model.constants

object QuestGFXIDLayerConstants {
    const val TUTORIALREWARD: Long = 51022
    const val INTRODUCTION: Long = 51021
    const val FEATURE_NEEDS: Long = 51033
    const val FEATURE_PERMISSIONS: Long = 51034
    const val FEATURE_BALANCE: Long = 51040
    const val INFRASTRUCTURE_INTRODUCTION_EDUCATION: Long = 50050
    const val INFRASTRUCTURE_INTRODUCTION: Long = 50044
    const val INFRASTRUCTURE_INTRODUCTION_KAIDEN: Long = 50045
    const val INFRASTRUCTURE_INTRODUCTION_KAIDEN_FRIENDS: Long = 50047
    const val INFRASTRUCTURE_INTRODUCTION_POLICE: Long = 50067
    const val INFRASTRUCTURE_INTRODUCTION_POLICECHIEF: Long = 50068
    const val CHARACTER_SARIKA_INTRODUCTION: Long = 50114
    const val INFRASTRUCTURE_FEATURE_SECURITY_DEVICES: Long = 50049
    const val INFRASTRUCTURE_FEATURE_SUCCESS_CHANCE: Long = 50048
    const val INFRASTRUCTURE_FEATURE_SECURITY_GRADES: Long = 50046
    const val IMPROVEMENT_FEATURE_BOOSTERPACKS: Long = 50091
    const val IMPROVEMENT_FEATURE_MANAGEMENT_LAYER: Long = 50092
    const val IMPROVEMENT_FEATURE_CURSOR_MODE: Long = 50093
    const val IMPROVEMENT_FEATURE_EFFECTS: Long = 50094
    const val BIG_FEATURE_CAPITALISTS: Long = 50113
    const val BIG_FEATURE_PRODUCTION_POINTS: Long = 51041
    const val BIG_FEATURE_PF2_BRIDGE: Long = 50120
    const val BIG_FEATURE_PF2_COASTAL_BUILDINGS: Long = 50121
    const val BIG_FEATURE_SUBLEVEL: Long = 50127
    const val BIG_FEATURE_MASTERY: Long = 50132
    val ALL = setOf(
        TUTORIALREWARD,
        INTRODUCTION,
        FEATURE_NEEDS,
        FEATURE_PERMISSIONS,
        FEATURE_BALANCE,
        INFRASTRUCTURE_INTRODUCTION_EDUCATION,
        INFRASTRUCTURE_INTRODUCTION,
        INFRASTRUCTURE_INTRODUCTION_KAIDEN,
        INFRASTRUCTURE_INTRODUCTION_KAIDEN_FRIENDS,
        INFRASTRUCTURE_INTRODUCTION_POLICE,
        INFRASTRUCTURE_INTRODUCTION_POLICECHIEF,
        CHARACTER_SARIKA_INTRODUCTION,
        INFRASTRUCTURE_FEATURE_SECURITY_DEVICES,
        INFRASTRUCTURE_FEATURE_SUCCESS_CHANCE,
        INFRASTRUCTURE_FEATURE_SECURITY_GRADES,
        IMPROVEMENT_FEATURE_BOOSTERPACKS,
        IMPROVEMENT_FEATURE_MANAGEMENT_LAYER,
        IMPROVEMENT_FEATURE_CURSOR_MODE,
        IMPROVEMENT_FEATURE_EFFECTS,
        BIG_FEATURE_CAPITALISTS,
        BIG_FEATURE_PRODUCTION_POINTS,
        BIG_FEATURE_PF2_BRIDGE,
        BIG_FEATURE_PF2_COASTAL_BUILDINGS,
        BIG_FEATURE_SUBLEVEL,
        BIG_FEATURE_MASTERY
    )
}
