package core.model.constants

object ServerTagConstants {
    const val GOOD_CONSTRUCTION: String = "GOOD_CONSTRUCTION"
    const val GOOD_NORMAL: String = "GOOD_NORMAL"
    const val GOOD_EVENT: String = "GOOD_EVENT"
    const val GOOD_SPECIAL: String = "GOOD_SPECIAL"
    const val GOOD_MEDAL: String = "GOOD_MEDAL"
    const val GOOD_DEXTRO: String = "GOOD_DEXTRO"
    const val GOOD_KEY: String = "GOOD_KEY"
    const val GROUND: String = "GROUND"
    const val STREET: String = "STREET"
    const val SQUARE: String = "SQUARE"
    const val DOCK: String = "DOCK"
    const val BOULDER: String = "BOULDER"
    const val PLAYFIELDBOULDER: String = "PLAYFIELDBOULDER"
    const val STREETBOULDER: String = "STREETBOULDER"
    const val ROCK: String = "ROCK"
    const val TREE: String = "TREE"
    const val BUILDING: String = "BUILDING"
    const val SHOP: String = "SHOP"
    const val RESIDENTIAL: String = "RESIDENTIAL"
    const val DECORATION: String = "DECORATION"
    const val PRODUCTION: String = "PRODUCTION"
    const val POWERPLANT: String = "POWERPLANT"
    const val SPECIAL: String = "SPECIAL"
    const val FIRE_DEPARTMENT: String = "FIRE_DEPARTMENT"
    const val POLICE_DEPARTMENT: String = "POLICE_DEPARTMENT"
    const val HOSPITAL: String = "HOSPITAL"
    const val SECURITY_DEVICE: String = "SECURITY_DEVICE"
    const val SCHOOL: String = "SCHOOL"
    const val CINEMA: String = "CINEMA"
    const val CHRISTMAS_TREE: String = "CHRISTMAS_TREE"
    const val CLIENT_OLYMPIC_STADIUM: String = "CLIENT_OLYMPIC_STADIUM"
    const val CLIENT_SCHEDULED_DROP: String = "CLIENT_SCHEDULED_DROP"
    const val BUILDING_TOWNHALL: String = "BUILDING_CONSTRUCTION_YARD"
    const val BUILDING_EVENTSQUARE: String = "BUILDING_EVENTSQUARE"
    const val BUILDING_ACTIVATOR: String = "ACTIVATOR"
    const val SHRUBBERY: String = "SHRUBBERY"
    const val MYSTERY: String = "MYSTERY"
    const val CLIENT_HIDE_LEVELUP: String = "CLIENT_HIDE_LEVELUP"
    const val PLAYFIELDITEM_HIGHLIGHT: String = "PLAYFIELDITEM_HIGHLIGHT"
    const val CLIENT_SORT_WEIGHT: String = "CLIENT_SORT_WEIGHT_"
    const val CLIENT_CUSTOM_URBIE: String = "CUSTOM_URBIE_"
    const val CLIENT_CUSTOM_CAR: String = "CUSTOM_CAR_"
    const val CLIENT_HIDE_GOOD: String = "CLIENT_HIDE_GOOD"
    const val CLIENT_ITEM_REBUY_PACK: String = "CLIENT_ITEM_REBUY_PACK"
    const val CLIENT_WHEEL_BUFF_TOKEN: String = "CLIENT_WHEEL_BUFF_TOKEN"
    const val CLIENT_WHEEL_SPIN_TOKEN: String = "CLIENT_WHEEL_SPIN_TOKEN"
    const val CLIENT_GOOD_WHEEL_TOKEN: String = "CLIENT_GOOD_WHEEL_TOKEN"
    const val CLIENT_GOOD_GRANITE: String = "CLIENT_GOOD_GRANITE"
    const val CLIENT_SUBLEVEL_BOOSTER_PACK: String = "CLIENT_SUBLEVEL_BOOSTER_PACK"
    const val CLIENT_PLAYFIELDITEM_PREMIUM: String = "CLIENT_PLAYFIELDITEM_PREMIUM"
    const val WHEEL_BUFF_MULTI: String = "WHEEL_BUFF_MULTI"
    const val CLIENT_RESOURCE_REBUY_PACK: String = "CLIENT_RESOURCE_REBUY_PACK"
    const val CLIENT_PAYMENT_PACK_STARTER: String = "CLIENT_PAYMENT_PACK_STARTER"
    const val CLIENT_PAYMENT_PACK_STUDENT: String = "CLIENT_PAYMENT_PACK_STUDENT"
    const val CLIENT_PAYMENT_PACK_PRODUCTION: String = "CLIENT_PAYMENT_PACK_PRODUCTION"
    const val CLIENT_PAYMENT_PACK_FIRST_AID: String = "CLIENT_PAYMENT_PACK_FIRST_AID"
    const val CLIENT_PAYMENT_PACK_GAMBLING: String = "CLIENT_PAYMENT_PACK_GAMBLING"
    const val CLIENT_PAYMENT_PACK_RENT_COLLECTOR: String = "CLIENT_PAYMENT_PACK_RENT_COLLECTOR"
    const val VIRTUAL_EXPANSION: String = "onlyClientUseExpansion"
    const val IM_RESIDENTIAL_BASIC_EFFICIENCY: String = "RESIDENTIALBASICEFFICIENCY"
    const val IM_MOOD_CONSUMPTION_EFFICIENCY: String = "MOODCONSUMPTIONEFFICIENCY"
    const val IM_RESIDENTIAL_TIMER_EFFICIENCY: String = "RESIDENTIALTIMEREFFICIENCY"
    const val IM_ENERGY_CONSUMPTION_EFFICIENCY: String = "ENERGYCONSUMPTIONEFFICIENCY"
    const val IM_RESIDENTIAL_NEED_EFFICIENCY: String = "RESIDENTIALNEEDEFFICIENCY"
    const val IM_RESIDENTIAL_XP_EFFICIENCY: String = "RESIDENTIALXPEFFICIENCY"
    const val WHEEL_REWARD_HIGH: String = "WHEEL_REWARD_HIGH"
    const val WHEEL_REWARD_JACKPOT: String = "WHEEL_REWARD_JACKPOT"
    const val WHEEL_REWARD_NORMAL: String = "WHEEL_REWARD_NORMAL"
    const val BUFF_HARVEST: String = "BUFF_HARVEST"
    const val TIME: String = "TIME"
    const val CLIENT_BONUS_DAY: String = "CLIENT_BONUSDAY"
    const val PAYMENT_UPSELL: String = "UPSELL"
    const val PAYMENT_REACTIVATION: String = "REACTIVATIOn"
    const val PAYMENT_NON_PAY: String = "NON_PAY"
    const val PAYMENT_NEW_NON_PAY: String = "NEW_NON_PAY"
    const val INSTANT_FINISH: String = "INSTANT_FINISH"
    val ALL = setOf(
        GOOD_CONSTRUCTION,
        GOOD_NORMAL,
        GOOD_EVENT,
        GOOD_SPECIAL,
        GOOD_MEDAL,
        GOOD_DEXTRO,
        GOOD_KEY,
        GROUND,
        STREET,
        SQUARE,
        DOCK,
        BOULDER,
        PLAYFIELDBOULDER,
        STREETBOULDER,
        ROCK,
        TREE,
        BUILDING,
        SHOP,
        RESIDENTIAL,
        DECORATION,
        PRODUCTION,
        POWERPLANT,
        SPECIAL,
        FIRE_DEPARTMENT,
        POLICE_DEPARTMENT,
        HOSPITAL,
        SECURITY_DEVICE,
        SCHOOL,
        CINEMA,
        CHRISTMAS_TREE,
        CLIENT_OLYMPIC_STADIUM,
        CLIENT_SCHEDULED_DROP,
        BUILDING_TOWNHALL,
        BUILDING_EVENTSQUARE,
        BUILDING_ACTIVATOR,
        SHRUBBERY,
        MYSTERY,
        CLIENT_HIDE_LEVELUP,
        PLAYFIELDITEM_HIGHLIGHT,
        CLIENT_SORT_WEIGHT,
        CLIENT_CUSTOM_URBIE,
        CLIENT_CUSTOM_CAR,
        CLIENT_HIDE_GOOD,
        CLIENT_ITEM_REBUY_PACK,
        CLIENT_WHEEL_BUFF_TOKEN,
        CLIENT_WHEEL_SPIN_TOKEN,
        CLIENT_GOOD_WHEEL_TOKEN,
        CLIENT_GOOD_GRANITE,
        CLIENT_SUBLEVEL_BOOSTER_PACK,
        CLIENT_PLAYFIELDITEM_PREMIUM,
        WHEEL_BUFF_MULTI,
        CLIENT_RESOURCE_REBUY_PACK,
        CLIENT_PAYMENT_PACK_STARTER,
        CLIENT_PAYMENT_PACK_STUDENT,
        CLIENT_PAYMENT_PACK_PRODUCTION,
        CLIENT_PAYMENT_PACK_FIRST_AID,
        CLIENT_PAYMENT_PACK_GAMBLING,
        CLIENT_PAYMENT_PACK_RENT_COLLECTOR,
        VIRTUAL_EXPANSION,
        IM_RESIDENTIAL_BASIC_EFFICIENCY,
        IM_MOOD_CONSUMPTION_EFFICIENCY,
        IM_RESIDENTIAL_TIMER_EFFICIENCY,
        IM_ENERGY_CONSUMPTION_EFFICIENCY,
        IM_RESIDENTIAL_NEED_EFFICIENCY,
        IM_RESIDENTIAL_XP_EFFICIENCY,
        WHEEL_REWARD_HIGH,
        WHEEL_REWARD_JACKPOT,
        WHEEL_REWARD_NORMAL,
        BUFF_HARVEST,
        TIME,
        CLIENT_BONUS_DAY,
        PAYMENT_UPSELL,
        PAYMENT_REACTIVATION,
        PAYMENT_NON_PAY,
        PAYMENT_NEW_NON_PAY,
        INSTANT_FINISH
    )
}
