package core.model.constants

object ServerPhaseType {
    const val CREATE_ACTIVATE: String = "CREATE_ACTIVATE"
    const val ACTIVATION: String = "ACTIVATION"
    const val CREATE_CONSTRUCTION: String = "CREATE_CONSTRUCTION"
    const val MYSTERY_CONSTRUCTION: String = "MYSTERY_CONSTRUCTION"
    const val CREATE_PLACE_NORMAL: String = "CREATE_PLACE_NORMAL"
    const val CREATE_PLACE_PERMISSION: String = "CREATE_PLACE_PERMISSION"
    const val RESIDENTIAL: String = "RESIDENTIAL"
    const val RANDOM_REWARD_HARVEST: String = "RANDOM_REWARD_HARVEST"
    const val UPGRADE: String = "UPGRADE"
    const val PRODUCTION_START: String = "PRODUCTION_START"
    const val PRODUCTION: String = "PRODUCTION"
    const val EDUCATION: String = "EDUCATION"
    const val RESIDENT: String = "RESIDENT"
    const val DESTRUCTIONPHASE_REMOVE_DECORATION: String = "REMOVE_DECORATION"
    const val DESTRUCTIONPHASE_REMOVE_BOULDER: String = "REMOVE_BOULDER"
    const val DESTRUCTIONPHASE_REMOVE_BUILDING: String = "REMOVE_BUILDING"
    const val INSTANT_FINISH: String = "INSTANT_FINISH"
    const val INSTANT_CONSTRUCTION: String = "INSTANT_CONSTRUCTION"
    const val INSTANT_UPGRADE: String = "INSTANT_UPGRADE"
    const val INSTANT_REMOVE_BOULDER: String = "INSTANT_REMOVE_BOULDER"
    const val CLIENTSIDE_VIRTUAL: String = "CLIENTSIDE_VIRTUAL"
    const val INSTANT_DEPARTMENT_UPGRADE: String = "INSTANT_DEPARTMENT_UPGRADE"
    const val EXPANSION: String = "EXPANSION"
    val ALL = setOf(
        CREATE_ACTIVATE,
        ACTIVATION,
        CREATE_CONSTRUCTION,
        MYSTERY_CONSTRUCTION,
        CREATE_PLACE_NORMAL,
        CREATE_PLACE_PERMISSION,
        RESIDENTIAL,
        RANDOM_REWARD_HARVEST,
        UPGRADE,
        PRODUCTION_START,
        PRODUCTION,
        EDUCATION,
        RESIDENT,
        DESTRUCTIONPHASE_REMOVE_DECORATION,
        DESTRUCTIONPHASE_REMOVE_BOULDER,
        DESTRUCTIONPHASE_REMOVE_BUILDING,
        INSTANT_FINISH,
        INSTANT_CONSTRUCTION,
        INSTANT_UPGRADE,
        INSTANT_REMOVE_BOULDER,
        CLIENTSIDE_VIRTUAL,
        INSTANT_DEPARTMENT_UPGRADE,
        EXPANSION
    )
}
